### ISSUE TITLE
3.2.10-1 doesn't work after reboot on CentOS 7

### ISSUE THREAD

**Issue by kustodian** [iuscommunity-pkg/redis32u#2]
Because `/var/run/redis` directory is created with `tmpfiles.d` with `755` permissions, and this directory is also created with the `redis.service` file with different permissions `RuntimeDirectoryMode=0750`, so systemd doesn't allow that and just fails and deletes `/var/run/redis`. Starting redis again then works, because the dir doesn't exist and systemd creates it because of the unit file.

I tried if the upgrading from version <=3.2.9 to 3.2.10 would fail, but it doesn't because Redis first deletes that dir, then starts again, so that is fine. It does throw some error, but restart correctly.

Anyway to fix this issue you should remove the creation of `/usr/lib/tmpfiles.d/redis.conf` because now the unit file creates that dir itself.

**Comment by b-harper** [comment]
@kustodian,

Thanks for reporting this issue.  I am able to reproduce the reboot issue.  On a test server, I installed redis32u-3.2.10-1.  It could start/stop/restart just fine.  Then got the following after a reboot:

<details>

```
$ sudo systemctl status redis -l
● redis.service - Redis persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/redis.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/redis.service.d
           └─limit.conf
   Active: failed (Result: exit-code) since Fri 2017-08-18 08:21:11 CDT; 1min 41s ago
  Process: 1085 ExecStop=/usr/libexec/redis-shutdown (code=exited, status=233/RUNTIME_DIRECTORY)
  Process: 1077 ExecStart=/usr/bin/redis-server /etc/redis.conf --daemonize no (code=exited, status=233/RUNTIME_DIRECTORY)
 Main PID: 1077 (code=exited, status=233/RUNTIME_DIRECTORY)

Aug 18 08:21:11 test7.ius.io systemd[1]: Started Redis persistent key-value database.
Aug 18 08:21:11 test7.ius.io systemd[1]: Starting Redis persistent key-value database...
Aug 18 08:21:11 test7.ius.io systemd[1077]: Failed at step RUNTIME_DIRECTORY spawning /usr/bin/redis-server: File exists
Aug 18 08:21:11 test7.ius.io systemd[1]: redis.service: main process exited, code=exited, status=233/RUNTIME_DIRECTORY
Aug 18 08:21:11 test7.ius.io systemd[1085]: Failed at step RUNTIME_DIRECTORY spawning /usr/libexec/redis-shutdown: File exists
Aug 18 08:21:11 test7.ius.io systemd[1]: redis.service: control process exited, code=exited status=233
Aug 18 08:21:11 test7.ius.io systemd[1]: Unit redis.service entered failed state.
Aug 18 08:21:11 test7.ius.io systemd[1]: redis.service failed.

$ sudo systemctl start redis

$ sudo systemctl status redis -l
● redis.service - Redis persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/redis.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/redis.service.d
           └─limit.conf
   Active: active (running) since Fri 2017-08-18 08:23:03 CDT; 2s ago
  Process: 1085 ExecStop=/usr/libexec/redis-shutdown (code=exited, status=233/RUNTIME_DIRECTORY)
 Main PID: 2539 (redis-server)
   CGroup: /system.slice/redis.service
           └─2539 /usr/bin/redis-server 127.0.0.1:6379                

Aug 18 08:23:03 test7.ius.io systemd[1]: Started Redis persistent key-value database.
Aug 18 08:23:03 test7.ius.io systemd[1]: Starting Redis persistent key-value database...
```

</details>

I will continue to look into this issue and report back.

**Comment by kustodian** [comment]
You can also see this commit as a reference: https://github.com/lamby/pkg-redis/commit/1cecea5abcb2ce05beacd4347977634d06c59cef

Just removing `/usr/lib/tmpfiles.d/redis.conf` should be the best way to solve this problem. And since upgrade from older versions to 3.2.10-1 works all is good.

**Comment by b-harper** [comment]
Yup, I already tested and committed in 2210b59.  Just starting to build packages.

**Comment by b-harper** [comment]
Updated packages have been built and will get pushed into the stable repositories during tonight's automation.  Typically, we would use the testing repositories to allow for testing.  Given the nature of this issue and my testing, we will bypass the testing repositories for this update.  

Note, this issue does not effect EL6.
